import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
})

const rooftop = localFont({
  src: [
    {
      path: '../assets/rooftop-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/rooftop-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/rooftop-extrabold.woff2',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-rooftop',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${rooftop.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
